project:
  type: website

website:
  title: "Data Science For Finance"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
      - text: Lectures
        menu:
            - href: 'lectures/lecture_00/lecture_00.qmd'
              text: Lecture 00 
            - href: 'lectures/lecture_01/lecture_01.qmd'
              text: Lecture 01 - Introduction to Python
            - href: 'lectures/lecture_02/lecture_02.qmd'
              text: Lecture 02 - Data types and structures
            - href: 'lectures/lecture_03/lecture_03.qmd'
              text: Lecture 03 - Control structures
            - href: 'lectures/lecture_04/lecture_04.qmd'
              text: Lecture 04 - Functions
            - href: 'lectures/lecture_05/lecture_05.qmd'
              text: Lecture 05 - Object Oriented Programming
            - href: 'lectures/lecture_06/lecture_06.qmd'
              text: Lecture 06 - Libraries
            - href: 'lectures/lecture_07/lecture_07.qmd'
              text: Lecture 07 - Numerical Computing
            - href: 'lectures/lecture_08/lecture_08.qmd'
              text: Lecture 08 - Data Manipulation
            - href: 'lectures/lecture_09/lecture_09.qmd'
              text: Lecture 09 - Input/output
            - href: 'lectures/lecture_10/lecture_10.qmd'
              text: Lecture 10 - Network Analytics
            - href: ''
              text: Lecture 11 - Time Series
            - href: ''
              text: Lecture 12 - Machine Learning
            - href: ''
              text: Lecture 13 - Advanced Machine Learning
      - href: "https://app.alldayta.com/katholieke-universiteit-leuven/ds4f"
        text: All Day TA

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-location: left
    # number-sections: true

bibliography: refs.bib



